### PR TITLE
WIP: Dug 8 osfv

### PR DESCRIPTION
**Pull request by macpijan**

### CODE REVIEW

**Comment by macpijan** [comment]
@pietrushnic I would appreciate if you later take a look at graphics: https://github.com/Dasharo/presentations/pull/82/files#diff-b5347f9be34508aee27e398c931a68b3c0f828fa0b56cddfd03312f25dc807af

to confirm my refactor for the tool did not break your case.

**Comment by macpijan** [comment]
@DaniilKl I have added DTS repos as well to PRs stats: https://github.com/Dasharo/presentations/pull/82/files#diff-2853398b19c88d1620807bb3ac75a0bcb90bb687e07b4c4cd3850b26e8315452

You might be interested in including them to your presentatoin.

**Comment by pietrushnic** [comment]
@macpijan, the stats were changed slightly, so I would like to only those modifications if it is confirmed that they are correct. BTW why did you add my graphics? Just remove those from the PR. Maybe rebase on most recent version of dug_8?

**Comment by macpijan** [comment]
> . BTW why did you add my graphics? J

So we can confirm here if the changes in the scripts do not break your case. I do not intend to merge it right now.

> Just remove those from the PR. Maybe rebase on most recent version of dug_8?

I will do that later, I am sure there will be still some more changes

**Comment by macpijan** [comment]
Replaced with: https://github.com/Dasharo/presentations/pull/84

Skipped replacing coreboot/edk2 stats, but they still look like in this MR.

**Pull request closed without merging**
